version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: sh
    command: -c 'mkdir -p /export/video-uploads && /usr/bin/minio server /export --console-address ":9001"'
    networks:
      - app-network

volumes:
  minio_data: