name: video-submission-form
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/michealrm/videosubmissionframe.git
    build_command: npm install
    run_command: npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    env:
      - key: NODE_ENV
        value: production