name: video-submission-form
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/michealrm/videosubmissionframe.git
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: STORAGE_ENDPOINT
        value: https://nyc3.digitaloceanspaces.com
      - key: STORAGE_ACCESS_KEY
        value: ${{ secrets.DIGITALOCEAN_SPACES_ACCESS_KEY }}
      - key: STORAGE_SECRET_KEY
        value: ${{ secrets.DIGITALOCEAN_SPACES_SECRET_KEY }}
      - key: STORAGE_BUCKET
        value: vsf-video-uploads
      - key: STORAGE_REGION
        value: nyc3
      - key: STORAGE_FORCE_PATH_STYLE
        value: false
      - key: NODE_ENV
        value: production